# Generated by Django 3.0.5 on 2020-07-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LampType',
            new_name='Type',
        ),
    ]
