# Generated by Django 3.0.5 on 2020-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0003_auto_20200702_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamps',
            name='socle',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
