# Generated by Django 3.0.5 on 2020-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0004_lamps_socle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamps',
            name='imgsrc',
            field=models.CharField(default='https://placehold.it/300x300', max_length=2000),
        ),
    ]
