# Generated by Django 3.0.5 on 2020-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0006_auto_20200702_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamps',
            name='imgsrc',
            field=models.CharField(default='https://placehold.it/420x327', max_length=2000),
        ),
    ]
