# Generated by Django 3.0.5 on 2020-07-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0007_auto_20200702_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamps',
            name='destination',
            field=models.ForeignKey(default='Нет назначения', on_delete=django.db.models.deletion.DO_NOTHING, to='lamp.Destination'),
        ),
    ]
