# Generated by Django 3.0.5 on 2020-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0008_auto_20200708_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamps',
            name='attributes',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='lamps',
            name='description',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='lamps',
            name='feature',
            field=models.CharField(default='Стандарт', max_length=100),
        ),
        migrations.AddField(
            model_name='lamps',
            name='feature_desc',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
