# Generated by Django 3.0.5 on 2020-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0010_auto_20200708_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamps',
            name='feature',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
