# Generated by Django 3.0.5 on 2020-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0012_cars_gen_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.CharField(default='http://placehold.it/50x50', max_length=3000),
        ),
    ]
