# Generated by Django 3.0.8 on 2020-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0015_cars_mark_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamps',
            name='f_tag',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
