# Generated by Django 3.1.3 on 2020-12-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HimiyaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default=None)),
                ('imgurl', models.ImageField(upload_to='static/images/himiya')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='himiya.category')),
            ],
        ),
    ]
