# Generated by Django 3.1.3 on 2020-12-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('himiya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='HimiyaCategory',
        ),
    ]
