# Generated by Django 3.1.3 on 2021-02-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('himiya', '0002_auto_20201230_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himiyaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='himiya.himiyacategory'),
        ),
        migrations.AlterField(
            model_name='himiyaitem',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
