# Generated by Django 3.1.3 on 2021-02-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=300)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(default=None)),
                ('imgurl', models.ImageField(upload_to='static/images/himiya')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accessories.accessoriescategory')),
            ],
        ),
    ]
