# Generated by Django 3.0.8 on 2020-10-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dvbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dvcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=100)),
                ('gen_img', models.CharField(default='https://placehold.it/420x327', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Dvkreplenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dvser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dvtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dvornik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('imgsrc', models.CharField(default='https://placehold.it/420x327', max_length=2000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvbrand')),
                ('cars', models.ManyToManyField(to='dvorniki.Dvcar')),
                ('dvtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvtype')),
                ('kreplenie', models.ManyToManyField(to='dvorniki.Dvkreplenie')),
                ('ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvser')),
            ],
        ),
    ]
