# Generated by Django 3.0.8 on 2020-10-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dvcar',
            name='model',
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Dvmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmark')),
            ],
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmodel'),
        ),
    ]
