# Generated by Django 3.0.8 on 2020-10-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0002_auto_20201006_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvcar',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmark'),
        ),
        migrations.AlterField(
            model_name='dvmark',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dvmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
