# Generated by Django 3.0.8 on 2020-10-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0003_auto_20201006_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvmodel',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Dvgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvgen'),
        ),
    ]
