# Generated by Django 3.0.8 on 2020-10-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0004_auto_20201006_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvmodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmark'),
        ),
    ]
