# Generated by Django 3.0.8 on 2020-10-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0005_auto_20201007_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvgen'),
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvmark'),
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvmodel'),
        ),
        migrations.AlterField(
            model_name='dvgen',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvmark'),
        ),
        migrations.AlterField(
            model_name='dvgen',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvmodel'),
        ),
        migrations.AlterField(
            model_name='dvmodel',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvorniki.Dvmark'),
        ),
    ]
