# Generated by Django 3.0.8 on 2020-10-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0007_auto_20201007_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvcar',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='dvcar',
            name='model',
        ),
        migrations.RemoveField(
            model_name='dvgen',
            name='mark',
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvgen'),
        ),
        migrations.AlterField(
            model_name='dvgen',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmodel'),
        ),
        migrations.AlterField(
            model_name='dvmodel',
            name='mark',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dvorniki.Dvmark'),
        ),
    ]
