# Generated by Django 3.0.8 on 2020-10-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0008_auto_20201007_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvcar',
            name='mark',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmark'),
        ),
        migrations.AddField(
            model_name='dvcar',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmodel'),
        ),
        migrations.AlterField(
            model_name='dvcar',
            name='gen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvgen'),
        ),
        migrations.AlterField(
            model_name='dvgen',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmodel'),
        ),
        migrations.AlterField(
            model_name='dvmodel',
            name='mark',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmark'),
        ),
    ]
