# Generated by Django 3.0.8 on 2020-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0009_auto_20201007_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvornik',
            name='country',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dvornik',
            name='length',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dvornik',
            name='sku',
            field=models.CharField(default='', max_length=300),
        ),
    ]
