# Generated by Django 3.0.8 on 2020-10-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0010_auto_20201008_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvser',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvmark'),
        ),
    ]
