# Generated by Django 3.0.8 on 2020-10-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvorniki', '0011_dvser_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvser',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvorniki.Dvbrand'),
        ),
    ]
